### ISSUE TITLE
almost invisible selection

### ISSUE THREAD

**Issue by T3sT3ro** [highlightjs/base16-highlightjs#2]
https://github.com/highlightjs/base16-highlightjs/blob/27a6e6b3e548093b43f5576f98afcf71e696ac5a/themes/dracula.css#L52:L56

In IntelliJ, for examplpe, the selection colors are `#214283` for background and unset for foreground. I recommend doing it the same way, that is: 
```css
.hljs ::selection, .hljs::selection {
    background-color: #214283;  
    color: unset;
}
```

Proposed:
![image](https://user-images.githubusercontent.com/5300963/203857533-e324d50b-20ce-472c-bd61-e96edb1c8d49.png)

Current:
![image](https://user-images.githubusercontent.com/5300963/203857585-b4da3d88-a02e-4fbf-a898-c6fcb7269e28.png)
